name: Update Recent Commits

on:
  schedule:
    - cron: '0 * * * *'  # cada hora
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate recent commits
        uses: actions-js/profile-commits@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_commits: 5
          committer_username: Alejandro193
          readme_path: README.md
          marker: RECENT_COMMITS
          include_repos: true

      - name: Commit & Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: actions@github.com
          message: '📝 Update recent commits'
